#include "../include/setup.h"
#include "../include/data.h"
#include "../include/trigger.h"
#include "../include/SRAM.h"
#include "../include/io.h"
#include "../include/setup.h"
#include "../include/testing.h"
#include <iostream>
#include <wiringPi.h>
#include <wiringPiI2C.h>
#include <ctime>
using namespace std; 

/* 
PowerOnSelfTest:
Run test of loaded params 
Run test of critical components 
Return OK signal if ok
*/

bool POST(){
    int test_mode = 1; 

    Testing test(test_mode); 

    if ( not test.is_alive() ){
         return false;}
    
    return (
        test.i2c_setup() &
        test.trig_setup() & 
        test.trig_precision() &
        test.clock_setting()
    ); 

}

int main(int argc, char* argv[]){

    if(POST()){

        const char * CONFIG_FILE_PATH = "config/digi.config";
        
        if(argv[2]){
            run_num = stoi(argv[2]);}
        
        std::string output_fname;       // generated by code  

        initialize(CONFIG_FILE_PATH);

        // Initialize objects
        Data RunData;  
        Trigger Trg1 = Trigger(1); 
        Trigger Trg2 = Trigger(2); 
        SRAM RAM;
        
        int file_count = 0; 
        while(!isfile(".stop")){ 

            if (RunData.eventNum % events_perFile == 0 & record_data){  
                // redefine file name after incrementing counter

                output_fname = 
                    fname_prefix + "_" + 
                    std::to_string(file_count)+
                    ".txt";

                file_count++;
            };

            // enable SRAM sampling
            RAM.enable_sampling();

            // use run configs to enable/disable triggers
            if(trg1){Trg1.enable();}
            if(trg2){Trg2.enable();}
            if(extrg){enable_extrg();}

            // wait for OE* to go high -> indicates that 
            // trigger runout has gone high 
            while(ReadPin(OEbar)==1); 
            digitalWrite(DAQHalt,1);
            digitalWrite(DAQHalt,1);
            digitalWrite(DAQHalt,1);
            RunData.Read(); 
            RunData.Write((
                output_folder+"/"+output_fname).c_str()
                ); 
            RunData.eventNum++; 
            std::cout << '\r'<<"Events: "<< RunData.eventNum << std::flush;
        }
    }
}
